apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wvynh2luw-go 
  janus-idp.io/tekton: wvynh2luw-go
  backstage.io/kubernetes-id: wvynh2luw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wvynh2luw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  