apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wvynh2luw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wvynh2luw-go 
  name: wvynh2luw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wvynh2luw-go 
